services:
  fileprocessingapp:
    container_name: fileprocessingapp-container
    image: rmanimaran/fileprocessingapp:v1
    ports:
        - "5000:80"
    env_file:
        - .env
    networks:
        - fileprocessingapp-network

networks:
    fileprocessingapp-network:
        driver: bridge
  

