services:
    api.jaeger:
      image: jaegertracing/all-in-one:latest
      container_name: api.jaeger
      networks:
      - fileprocessingapp
      ports:
        - 4317:4317
        - 4318:4318
        - 16686:16686
      environment:
        - COLLECTOR_OTLP_ENABLED=true
    seq:
      image: datalust/seq:latest
      container_name: seq
      networks:
        - fileprocessingapp
      ports:
        - 5341:80
      environment:
        - ACCEPT_EULA=Y
        - SEQ_FIRSTRUN_ADMINPASSWORD=admin123
      volumes:
        - seq-data:/data
volumes:
  seq-data:

networks:
  fileprocessingapp:
    driver: bridge