apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-logs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/logs
    type: DirectoryOrCreate
