apiVersion: v1
data:
  queue-connection: base64_encoded_connstr_here
kind: Secret
metadata:
  creationTimestamp: "2025-10-01T00:30:35Z"
  name: storage-secret
  namespace: default
  resourceVersion: "1925046"
  uid: 1c22883b-ce2f-46c6-b79c-d629dace796e
type: Opaque